module.exports = [
  { value: null, result: false },
  { value: undefined, result: false },
  { value: () => {}, result: false },
  { value: 1, result: false },
  { value: [], result: false },
  { value: '', result: true },
  { value: 'abc', result: true },
  { value: 'abc', options: { startsWith: 'a' }, result: true },
  { value: 'abc', options: { startsWith: 'b' }, result: false },
  { value: 'abc', options: { endsWith: 'c' }, result: true },
  { value: 'abc', options: { endsWith: 'd' }, result: false },
  { value: 'abc', options: { startsWith: 'b', endsWith: 'c' }, result: false },
  { value: 'abc', options: { startsWith: 'a', endsWith: 'd' }, result: false },
  { value: 'abc', options: { startsWith: 'a', endsWith: 'c' }, result: true },
];
